# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --force
    - run: |
       cat <<EOT > ${{ github.workspace }}/.env
       REACT_APP_API= ${{ secrets.REACT_APP_API }}
       NODE_ENV=developement
       REACT_APP_SENDGRID_API_KEY="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"
       REACT_APP_CDN="<https://timerecordingtool.blob.core.windows.net/timerecordingtool/>"
       # AWS S3 Bucket Link
       # REACT_APP_CDN="<https://techpyro-bucket.sgp1.cdn.digitaloceanspaces.com/persobase/>"
       REACT_APP_WHISTLEBLOWING_URL=https://whistleblowing.perso-base.com
       EOT
    - run: npm run build --if-present
    - run: pm2 restart next-app
